[project]
name = "personalrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Chanchal82", email = "choudharychanchal1432@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.4.2",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-google-genai>=4.4.0",
    "langchain-text-splitters>=1.1.2",
    "pypdf>=6.19.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
personalrag = "personalrag:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
